import { Offer } from '../offers.interfaces'
import { Agreement } from '../offers.enums'
import { Technology, ExperienceLevel, City } from '../../../shared/shared.enums'

export class OffersService {
    private offers: Offer[] = [
        {companyName: "Intel", companySize:10000, companyLogo: "logo", companyAddress:{streetName:"Lotników Polskich", buildingNumber: 59, city: "Gdańsk"}, position:"programista", salary:{lowerLimit: 2000, upperLimit: 5000}, tags:["praca", "intel", "kasa"], routingTag: "IntelPRACA", experience: ExperienceLevel.junior, agreementType: Agreement.Permanent, description:"praca w intelu dobrze płatna", insertionDate:new Date(2018, 3, 4), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "McDonald", companySize:200000, companyLogo: "logo", companyAddress:{streetName:"Dębowa", buildingNumber: 39, city: "Banino"}, position:"grafik", salary:{lowerLimit: 100, upperLimit: 5000}, tags:["praca", "super", "kasa"], routingTag: "McDonaldPRACA", experience: ExperienceLevel.junior, agreementType: Agreement.B2B, description:"praca dobrze płatna", insertionDate:new Date(2019, 3, 21), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Neoteric", companySize:100, companyLogo: "logo", companyAddress:{streetName:"Sienna", buildingNumber: 75, city: "Warszawa"}, position:"programista", salary:{lowerLimit: 15000, upperLimit: 20000}, tags:["praca", "fajna", "kasa"], routingTag: "Neo", experience: ExperienceLevel.mid, agreementType: Agreement.Temporary, description:"praca bardzo dobrze płatna", insertionDate:new Date(2019, 3, 18), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Tesso", companySize:15, companyLogo: "logo", companyAddress:{streetName:"Podole", buildingNumber: 60, city: "Kraków"}, position:"programista", salary:{lowerLimit: 12000, upperLimit: 13000}, tags:["praca", "porzadna", "pieniądze"], routingTag: "TEsso", experience: ExperienceLevel.senior, agreementType: Agreement.Permanent, description:"praca super dobrze płatna", insertionDate:new Date(2019, 3, 23), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Auchan", companySize:25, companyLogo: "logo", companyAddress:{streetName:"Tęczowa", buildingNumber: 7, city: "Wrocław"}, position:"sieciowiec", salary:{lowerLimit: 5000, upperLimit: 5500}, tags:["praca", "bardzo", "kasa"], routingTag: "Auchan", experience: ExperienceLevel.all, agreementType: Agreement.B2B, description:"praca hiper dobrze płatna", insertionDate:new Date(2019, 3, 12), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Intel", companySize:10000, companyLogo: "logo", companyAddress:{streetName:"Śląska", buildingNumber: 11, city: "Gdynia"}, position:"programista", salary:{lowerLimit: 2000, upperLimit: 5000}, tags:["praca", "intel", "kasa"], routingTag: "IntelPRACA", experience: ExperienceLevel.junior, agreementType: Agreement.Permanent, description:"praca w intelu dobrze płatna", insertionDate:new Date(2018, 3, 4), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "McDonald", companySize:200000, companyLogo: "logo", companyAddress:{streetName:"Bojkowska", buildingNumber: 37, city: "Gliwice"}, position:"grafik", salary:{lowerLimit: 100, upperLimit: 5000}, tags:["praca", "super", "kasa"], routingTag: "McDonaldPRACA", experience: ExperienceLevel.junior, agreementType: Agreement.B2B, description:"praca dobrze płatna", insertionDate:new Date(2019, 4, 18), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Neoteric", companySize:100, companyLogo: "logo", companyAddress:{streetName:"Kościuszki", buildingNumber: 82, city: "Wrocław"}, position:"programista", salary:{lowerLimit: 15000, upperLimit: 20000}, tags:["praca", "fajna", "kasa"], routingTag: "Neo", experience: ExperienceLevel.mid, agreementType: Agreement.Temporary, description:"praca bardzo dobrze płatna", insertionDate:new Date(2019, 4, 18), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Tesso", companySize:15, companyLogo: "logo", companyAddress:{streetName:"Grzybowska", buildingNumber: 43, city: "Warszawa"}, position:"programista", salary:{lowerLimit: 12000, upperLimit: 13000}, tags:["praca", "porzadna", "pieniądze"], routingTag: "TEsso", experience: ExperienceLevel.senior, agreementType: Agreement.Permanent, description:"praca super dobrze płatna", insertionDate:new Date(2019, 3, 23), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Auchan", companySize:25, companyLogo: "logo", companyAddress:{streetName:"Mostowa", buildingNumber: 11, city: "Poznań"}, position:"sieciowiec", salary:{lowerLimit: 5000, upperLimit: 5500}, tags:["praca", "bardzo", "kasa"], routingTag: "Auchan", experience: ExperienceLevel.all, agreementType: Agreement.B2B, description:"praca hiper dobrze płatna", insertionDate:new Date(2019, 2, 12), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Intel", companySize:10000, companyLogo: "logo", companyAddress:{streetName:"Targowa", buildingNumber: 35, city: "Łódź"}, position:"programista", salary:{lowerLimit: 2000, upperLimit: 5000}, tags:["praca", "intel", "kasa"], routingTag: "IntelPRACA", experience: ExperienceLevel.junior, agreementType: Agreement.Permanent, description:"praca w intelu dobrze płatna", insertionDate:new Date(2018, 3, 4), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "McDonald", companySize:200000, companyLogo: "logo", companyAddress:{streetName:"Mikołaja Kopernika", buildingNumber: 95, city: "Białystok"}, position:"grafik", salary:{lowerLimit: 100, upperLimit: 5000}, tags:["praca", "super", "kasa"], routingTag: "McDonaldPRACA", experience: ExperienceLevel.junior, agreementType: Agreement.B2B, description:"praca dobrze płatna", insertionDate:new Date(2019, 4, 18), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Neoteric", companySize:100, companyLogo: "logo", companyAddress:{streetName:"Żurawia", buildingNumber: 71, city: "Białystok"}, position:"programista", salary:{lowerLimit: 15000, upperLimit: 20000}, tags:["praca", "fajna", "kasa"], routingTag: "Neo", experience: ExperienceLevel.mid, agreementType: Agreement.Temporary, description:"praca bardzo dobrze płatna", insertionDate:new Date(2019, 4, 18), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Tesso", companySize:15, companyLogo: "logo", companyAddress:{streetName:"Wyzwolenia", buildingNumber: 13, city: "Olsztyn"}, position:"programista", salary:{lowerLimit: 12000, upperLimit: 13000}, tags:["praca", "porzadna", "pieniądze"], routingTag: "TEsso", experience: ExperienceLevel.senior, agreementType: Agreement.Permanent, description:"praca super dobrze płatna", insertionDate:new Date(2019, 3, 23), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Auchan", companySize:25, companyLogo: "logo", companyAddress:{streetName:"Warszawska", buildingNumber: 18, city: "Rzeszów"}, position:"sieciowiec", salary:{lowerLimit: 5000, upperLimit: 5500}, tags:["praca", "bardzo", "kasa"], routingTag: "Auchan", experience: ExperienceLevel.all, agreementType: Agreement.B2B, description:"praca hiper dobrze płatna", insertionDate:new Date(2019, 2, 12), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]},
        {companyName: "Auchan", companySize:25, companyLogo: "logo", companyAddress:{streetName:"sadsad", buildingNumber: 18, city: "safasf"}, position:"sieciowiec", salary:{lowerLimit: 5000, upperLimit: 5500}, tags:["praca", "bardzo", "kasa"], routingTag: "Auchan", experience: ExperienceLevel.all, agreementType: Agreement.B2B, description:"praca hiper dobrze płatna", insertionDate:new Date(2019, 2, 12), requiredSkills:[{technology:Technology.Java, level: 5}, {technology:Technology.PHP, level: 4}]}
    ];
    
    constructor() {
    }

    public getOffers():Offer[]{
        return this.offers.slice();
    }

    public getOffer(tag:string):Offer{
        for(let tempOffer of this.offers){
            if(tempOffer.routingTag == tag){
                return tempOffer;
            }
        }
    }
}